spring.application.name=location-service


spring.data.mongodb.uri=mongodb+srv://bikku1234:CrisisAi@cluster0.bq4zyzk.mongodb.net/coredb?retryWrites=true&w=majority


logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.org.springframework.web=INFO

spring.data.redis.host=localhost
spring.data.redis.port=6379
server.port=9090