spring.application.name=AI-SERVICE
server.port=8087

spring.data.mongodb.uri=mongodb://localhost:27017/ai_db

# Groq API
groq.api.key=${GROQ_API_KEY}
groq.api.url=https://api.groq.com/openai/v1/chat/completions
groq.api.model=llama-3.1-8b-instant

# ? Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true


