
# ? Server Port
server.port=8761

# ? Application Name
spring.application.name=SERVICE-REGISTRY

# ? Eureka server khud ko register nahi karega
eureka.client.register-with-eureka=false

# ? Registry se data fetch nahi karega
eureka.client.fetch-registry=false

# ? Default URL (optional but good practice)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# ? Dashboard me clean view ke liye
eureka.instance.hostname=localhost

# ? Self-preservation mode (dev ke liye disable kar sakte ho)
eureka.server.enable-self-preservation=false

# ? Logs clean rakhne ke liye (optional)
logging.level.com.netflix.eureka=OFF
logging.level.com.netflix.discovery=OFF