
spring.application.name=core-service
server.port=8082


spring.data.mongodb.uri=mongodb+srv://bikku1234:CrisisAi@cluster0.bq4zyzk.mongodb.net/coredb?retryWrites=true&w=majority


logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.org.springframework.web=INFO